### ISSUE TITLE
reloadData() method

### ISSUE THREAD

**Issue by iMac0de** [HideakiTouhara/Poi#3]
Hello,

I have tested your Poi framwork in one of my project and it is very easy to use!

Howewere, I was trouble that there is no `reloadData()` method in order to be similar to a `UITableView` or `UICollectionView`. I think it could be a good feature to add.

Regards.

**Comment by ghost** [comment]
Hi,

Same issue, I reload the entire viewController to get new data.

I want to thank HideakiTouhara for this great tool.

Regards,
