### ISSUE TITLE
Views getting caught on screen after swipe

### ISSUE THREAD

**Issue by ghost** [HideakiTouhara/Poi#7]
Attached a screenshot
![img_0641](https://user-images.githubusercontent.com/33837719/47318888-e5535800-d612-11e8-8378-d52f95283e5c.jpg)

**Comment by HideakiTouhara** [comment]
Thank you for your opinion.
We can fix it to change card's destination.
Does anyone can do it?

**Comment by HideakiTouhara** [comment]
#10 fixed it.
